name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build Phase: Build the Docker image from the Dockerfile
      - name: Build Docker Image
        run: docker build -t my-docker-app:latest .

      # Test Phase: Run the container and execute tests inside it
      - name: Run Container and Execute Tests
        run: echo 'docker run -p 8080:80 --rm my-docker-app:latest'

      # Deployment Phase: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Tag the built image for Docker Hub
      - name: Tag Docker Image
        run: docker tag my-docker-app:latest ahmedevops/my-docker-app:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ahmedevops/my-docker-app:latest

      # (Optional) Deploy to Kubernetes using your deployment manifests
      #- name: Deploy to Kubernetes
        #run: |
          #echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          #kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml
